### ISSUE TITLE
Can't compile ManiacManfred demo with UE 4.26.1

### ISSUE THREAD

**Issue by revolvingalec** [ArticySoftware/DemoProjectForUnreal-ManiacManfred#3]
Hello!

Specs:
MM demo from this github rep + UE 4.26.1 (Articy Importer plugin from Unreal Marketplace installed) + Visual Studio 2019 with C++ libs.

When I try to open MM demo for the first time I got this warning:
![Screenshot 2021-04-16 182722](https://user-images.githubusercontent.com/82667587/115047803-89b36e00-9ee1-11eb-87f2-cf7d6ad0f4ee.jpg)
If I press "Yes" - it starts compiling for 20-30 seconds till the error happens:
![Screenshot 2021-04-16 184444](https://user-images.githubusercontent.com/82667587/115050002-fd567a80-9ee3-11eb-80d1-dd957faf31af.jpg)

Thanks in advance.

**Comment by christian-schildt** [comment]
Hi Tokas225,

What errors are in the log when compiling the project directly in Visual Studio?
Since this demo project already contains the Github version of the plugin, your problem might be related to the Marketplace version of the plugin. Does the project open when you temporarily delete the Marketplace version?


Best regards,

Christian

**Comment by revolvingalec** [comment]
Hi, @christian-schildt!

It's kind a ridiculus, but the real problem was about PATHs. By default my archiver software extract archives to the folder, named exactly as an initial archive file. So, take a closer look:

1. if I extract it by default, I got PATH to the unreal project file like "C:\Users\Username\Downloads\DemoProjectForUnreal-ManiacManfred-master\DemoProjectForUnreal-ManiacManfred-master\ManiacManfred.uproject" - that way project is unbuildable (attaching a log file below, "case-1")
2. if I delete such folder dupliction sctructure to get PATH like "C:\Users\Username\Downloads\DemoProjectForUnreal-ManiacManfred-master\ManiacManfred.uproject" - **everything builds ok and I got project up and running in my UE4.26.1**
3. if I extract only project files without parent folder and got PATH like this: "C:\Users\Username\Downloads\1\ManiacManfred.uproject" - I again can't build project, but got a way larger log of errors (attaching log file below as well, "case-2")

I also can confirm, that it happens independently on existence/non-existence of Marketplace version in UE4 plugins folder.

So, I got my problem kind a solved, thank you, but you should definitly check out possible PATH-dependent code which affects buildability. It's look like that something in the project is extremely dependent on:

- parent folder not called as number like "1" (if folder called "folder" - project builds fine)
- duplication of "DemoProjectForUnreal-ManiacManfred-master" structure in PATH to unreal project file

I hope my little research was helpful to you as well. If you can now reproduse error I got using my upper words - you can close this issue as well and fix roots of discovered problem in your spare time. Thanks again. 

[ManiacManfred_case-1.log](https://github.com/ArticySoftware/DemoProjectForUnreal-ManiacManfred/files/6343146/ManiacManfred_case-1.log)
[ManiacManfred_case-2.log](https://github.com/ArticySoftware/DemoProjectForUnreal-ManiacManfred/files/6343147/ManiacManfred_case-2.log)

**Comment by christian-schildt** [comment]
Hi Tokas225,

Glad to hear that it works now.
Thanks for the further information. We will take closer look at the roots of the path-dependent issues soon.


Best regards,

Christian
